### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ippeiman** [ippeiman/furima-39106#20]
# 自身のフリマアプリのURL
https://furima-39106.onrender.com
# Basic認証のIDとパスワード
ID:ippei 
パスワード:2928
# 出品者用のメールアドレスとパスワード
メールアドレス:ippei@com
パスワード:ippeiman6
# 購入者用のメールアドレスとパスワード
メールアドレス:tamitami@com
パスワード:tami1234

**Comment by shodai-ito** [comment]
@ippeiman さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
「新品、未使用」の区切りを「・」に揃えて統一感を出しましょう。（カテゴリーは「・」で区切っているため）
<img width="579" alt="スクリーンショット 2023-07-27 9 28 41" src="https://github.com/ippeiman/furima-39106/assets/62537107/1348f7cd-3d49-41f2-b72c-539f597b8d9c">

- [x] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
「送料払い」という言葉には馴染みがないため、送料込みとしておきましょう。
<img width="594" alt="スクリーンショット 2023-07-27 9 28 52" src="https://github.com/ippeiman/furima-39106/assets/62537107/3b99d3ff-c8b2-474c-9092-a71bc2b5a676">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ippeiman** [comment]
# what
フリマアプリ挙動確認の修正完了しました。
# why
フリマアプリを正常に動作させるため。

**Comment by shodai-ito** [comment]
@ippeiman さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
